### ISSUE TITLE
[BUG] Seems like something went wrong trying to get the project settings: undefined (vscode.general.bugReport)

### ISSUE THREAD

**Issue by Bertverbeek4PS** [cosmoconsult/alpaca#1]
**Describe the bug**
When I can to create a container with the Cosmo Alpaca Preview I get the error:
Seems like something went wrong trying to get the project settings: undefined

**To Reproduce**
1. Fork the BusinessCentralApps repo
2. Go to BusinessCentralApps -> Apps
3. Create container.

**Expected behavior**
Container will be created

**Screenshots**
![image](https://github.com/cosmoconsult/alpaca/assets/71499421/02747496-3c97-4725-9fc6-d6a59ed27100)

**System Information**
 - OS: [e.g. Windows, MacOS, Linux]
 - Alpaca Version (VS Code Extension) v0.8.3

**Comment by lippertmarkus** [comment]
@Bertverbeek4PS thanks for reporting, we found the issue and will let you know here when we rolled out the fix.

**Comment by ps610** [comment]
@Bertverbeek4PS we rolled out the fix now.
