### ISSUE TITLE
[BUG] Containers not showing in project (vscode.general.bugReport)

### ISSUE THREAD

**Issue by tscottjendev** [cosmoconsult/alpaca#10]
**Describe the bug**
When viewing the addin control, under projects/containers my container does not show up.  However it is in the list in the of containers section

**To Reproduce**
1. Go to Addin Control
2. Expand to the containers folder within projects
3. No Containers displayed

**Expected behavior**
Would expect the containers to be listed 

**Screenshots**
![image](https://github.com/user-attachments/assets/1b8ea135-8168-40c4-bcfe-3972a65c9571)

**System Information**
 - OS: Windows 10
 - Alpaca Version (VS Code Extension) 0.26.0

**Additional context**

**Comment by lippertmarkus** [comment]
Looking into it

**Comment by lippertmarkus** [comment]
A recent change lead to the upper list only showing containers created from the currently set default branch. We'll revert the change and will show all containers from all branches there again.

**Comment by lippertmarkus** [comment]
v0.27.0 of the Alpaca extension fixes the issue, thanks for reporting!
