### ISSUE TITLE
[QUESTION] Agent Pool not found

### ISSUE THREAD

**Issue by ahenkel** [cosmoconsult/alpaca#12]
Hi where,

i got a problem then evaluating alpaca. I created a project with a repo. The Pipeline fails on creating the agent. The error is like: can not find agent pool {project name}. But the agent pool exists. I tried to create multiple projects and app-repos. It works only in 1 of 10 cases.

Can you give me tip?

Thanks in advance.

**Comment by lippertmarkus** [comment]
Hi, sounds like your build service doesn't have access to the Agent Pool. Can you check
Project Settings > Agent Pools > [Agent pool named like the project] > Security 

In the "Organization" permissions it should show the Build Service user with Admin permissions. Those should be automatically configured during project creation but maybe there's something going wrong for you:

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/47ea74aa-3f36-47f5-9416-193fe9fe49a3">

**Comment by lippertmarkus** [comment]
Can you add the build service permission on "organization" scope?

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/7286311a-6333-41b8-8dd8-40817fea1ec9">

**Comment by lippertmarkus** [comment]
We just rolled out an update that should fix cases where these permissions might are not correctly set. So manually adding it should hopefully no longer be necessary for your next Alpaca project, else please let us know!
