### ISSUE TITLE
[BUG] Error Creating Container (VSCode Error An error occurred)

### ISSUE THREAD

**Issue by tscottjendev** [cosmoconsult/alpaca#18]
**Describe the bug**
Getting error "Value cannot be null. (Parameter 'source') (Status 500: An error occurred). Errors: undefined" when creating a container for a new repo.
![image](https://github.com/user-attachments/assets/2a3c7f98-de17-4fab-91d0-238e32f82428)

**To Reproduce**
1. With Alpaca PRE extension
2. Click + to create a new repo
3. Give it a name and make it private
4. Clone the new repo
5. Add an App
6. Click + on Containers for the new repo
7. Give it a name, select Sandbox

**Expected behavior**
Expect a container for the current version of the app to be created.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a3c7f98-de17-4fab-91d0-238e32f82428)

**System Information**
 - OS: Window 10
 - Alpaca Version (VS Code Extension) [e.g. 1.5.0] v0.31.0

**Additional context**
When I created the repo also got this error in the initial commit
![image](https://github.com/user-attachments/assets/fda1311d-b9ff-4fa5-a7f9-c8339221995e)

**Comment by lippertmarkus** [comment]
Thank you, my colleague is looking into it

**Comment by PatrickSchiefer** [comment]
@tscottjendev fix is ready and will be released tomorrow

**Comment by PatrickSchiefer** [comment]
@tscottjendev fix is rolled out. Container creation should work now
