### ISSUE TITLE
[BUG] Missing DLLs (vscode.general.bugReport)

### ISSUE THREAD

**Issue by tscottjendev** [cosmoconsult/alpaca#2]
**Describe the bug**
When following the [Contributing to the Microsoft Base App](https://youtu.be/7Mui2676mjg) video for a BC25 container, I am getting errors that appear to be related to missing dlls.

**To Reproduce**
1. Fork the last BusinessCentralApps repository
2. Follow the steps in the video to create the container and clone the repository, etc.
3. Download DLL package
4. Extract DLLs and copy them to the `.netpackages` folder
5. Reload VS Code to load the DLL's
6. Filter the Problem window to view only the errors. 
7. See missing .NET reference errors.
![image](https://github.com/cosmoconsult/alpaca/assets/102963427/010a2e7b-8d60-424d-ba97-7543b956174e)

**Expected behavior**
No .NET errors should appear if all the DLL's have been copied down.

**Screenshots**
On a older container, I think this is the DLL it is looking for.
![image](https://github.com/cosmoconsult/alpaca/assets/102963427/e1d82925-9d65-41d7-b894-9b5c2bd4bb0c)

**System Information**
 - OS: Windows 10 (and Win11)
 - Alpaca Version (VS Code Extension) [e.g. 1.5.0]
 - Name: COSMO Alpaca **Preview** Version 0.9.0

**Additional context**

**Comment by lippertmarkus** [comment]
Good morning, thanks for reporting! I'll try to reproduce the issue and report back

**Comment by tscottjendev** [comment]
FYI, there a few more errors but I assume they are related to the missing DLL
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/tscott/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/tscott/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Severity | File | Description | Error | Location
-- | -- | -- | -- | --
Error | BaseApp/JSONManagement.Codeunit.al | Argument 1: cannot convert from 'DotNet System.Xml.XmlElement"' to   'DotNet "System.Xml.XmlNode"'" | AL(AL0133) | [567:46]
Error | BaseApp/SignedXMLMgt.Codeunit.al | DotNet 'SignedXml' is missing | AL(AL0185) | [35:20]
Error | BaseApp/SignedXMLMgt.Codeunit.al | DotNet 'SignedXml' is missing | AL(AL0185) | [77:20]
Error | BaseApp/SignedXMLMgt.Codeunit.al | DotNet 'Reference' is missing | AL(AL0185) | [78:23]
Error | BaseApp/SignedXMLMgt.Codeunit.al | DotNet 'XmlDsigEnvelopedSignatureTransform' is missing | AL(AL0185) | [79:14]
Error | BaseApp/System/OpenXMLManagement.Codeunit.al | DotNet 'OpenXmlUnknownElement' is missing | AL(AL0185) | [383:32]
Error | BaseApp/CRM/Interaction/Attachment.Table.al | DotNet 'OutlookHelper' is missing | AL(AL0185) | [542:24]
Error | BaseApp/CRM/Interaction/Attachment.Table.al | 'RunOnClient' is not a valid attribute on variables of type 'None' | AL(AL0458) | [541:9]
Error | BaseApp/CRM/Interaction/Attachment.Table.al | DotNet 'OutlookStatusCode' is missing | AL(AL0185) | [544:17]
Error | BaseApp/CRM/Interaction/Attachment.Table.al | 'RunOnClient' is not a valid attribute on variables of type 'None' | AL(AL0458) | [543:9]
Error | BaseApp/CRM/Outlook/OutlookMessageFactory.Codeunit.al | DotNet 'IOutlookMessageFactory' is missing | AL(AL0185) | [16:32]
Error | BaseApp/CRM/Outlook/OutlookMessageFactory.Codeunit.al | 'RunOnClient' is not a valid attribute on variables of type 'None' | AL(AL0458) | [15:9]
Error | BaseApp/CRM/Outlook/OutlookMessageFactory.Codeunit.al | DotNet 'IOutlookMessage' is missing | AL(AL0185) | [19:56]
Error | BaseApp/CRM/Outlook/OutlookMessageFactory.Codeunit.al | DotNet 'IOutlookMessageFactory' is missing | AL(AL0185) | [27:67]
Error | BaseApp/CRM/Outlook/OutlookMessageFactory.Codeunit.al | DotNet 'OutlookMessageFactory' is missing | AL(AL0185) | [35:38]
Error | BaseApp/CRM/Outlook/OutlookMessageFactory.Codeunit.al | 'RunOnClient' is not a valid attribute on variables of type 'None' | AL(AL0458) | [34:9]
Error | BaseApp/OtherCapabilities/Email/Mail.Codeunit.al | DotNet 'IOutlookMessage' is missing | AL(AL0185) | [21:31]
Error | BaseApp/OtherCapabilities/Email/Mail.Codeunit.al | 'RunOnClient' is not a valid attribute on variables of type 'None' | AL(AL0458) | [20:9]
Error | BaseApp/System/DataExchange/JSONBuffer.Table.al | Argument 1: cannot convert from 'DotNet System.IO.StringReader"'   to 'DotNet "System.IO.TextReader"'" | AL(AL0133) | [90:57]
Error | BaseApp/System/DataExchange/JsonTextReaderWriter.Codeunit.al | Argument 1: cannot convert from 'DotNet System.IO.StringWriter"'   to 'DotNet "System.IO.TextWriter"'" | AL(AL0133) | [32:57]



</body>

</html>

**Comment by tscottjendev** [comment]
Also should note, the Win11 machine is right out of the box with only Office installed.  Nothing else.

**Comment by lippertmarkus** [comment]
@tscottjendev I talked to Microsoft, they removed the app code (that you're getting errors about) that requires the old `Microsoft.Dynamics.NAV.Integration.Office.dll` but they didn't push it to GitHub yet. I'll update you when they did.

**Comment by lippertmarkus** [comment]
Microsoft just updated the BusinessCentralApps repo. Please update your fork and local clone. I verified it, with that the errors are gone

**Comment by tscottjendev** [comment]
@lippertmarkus interestingly, I still get some .Net errors from a brand new clone/repo/dll download.  I did not recreate the container.

![image](https://github.com/cosmoconsult/alpaca/assets/102963427/c9fcecda-c71d-47e3-8e2a-dccbe0f29a10)

**Comment by lippertmarkus** [comment]
Can you try a VS Code restart?

**Comment by tscottjendev** [comment]
I have, twice.

**Comment by lippertmarkus** [comment]
I tried again, seems that you need to recreate your container to get the newer BC version 25.0.18680.0 and download DLLs from there. It contains different ones. With that I got 0 errors: 
<img width="1391" alt="image" src="https://github.com/cosmoconsult/alpaca/assets/1463140/0f5ad89d-04dd-4531-9491-522338e9fc64">

**Comment by lippertmarkus** [comment]
btw if you wonder: BC24 and BC25 containers are super slow because of https://github.com/microsoft/nav-docker/issues/549
Microsoft will look into this next week.

**Comment by tscottjendev** [comment]
Hmm, I can't seem to resolve this.  I recreated the container this morning and the getting the same list of .NET errors.  

If it matters this is on a Win11 machine.

**Comment by lippertmarkus** [comment]
Did you download DLLs again and is the code in your fork and your local clone up to date?

**Comment by tscottjendev** [comment]
> Did you download DLLs again and is the code in your fork and your local clone up to date?
Yes and the system.security.cryptography.xml.dll is in the downloads.

I didn't think the OS should be an issue but just through it out there.  

I will refresh everything again from scratch and see what is happening.

**Comment by tscottjendev** [comment]
I had to recreate everything (fork, local repo, container) but it has worked this time.  Thank you.
