### ISSUE TITLE
[BUG] When opening Copsmo Alpaca Preview get the error code: Response returned an error code (VSCode Error Not Found)

### ISSUE THREAD

**Issue by Bertverbeek4PS** [cosmoconsult/alpaca#22]
**Describe the bug**
When navigating to Cosmo Alpaca Preview I got the errors:
![image](https://github.com/user-attachments/assets/61078526-10c1-46c2-b9a7-9e50de5892b0)

**To Reproduce**
1. Go to Visual Studio Code (insider build
2. Click on Cosmos Alpaca (preview)
4. See error (only the first time

**System Information**
 - Windows 11
 - Alpaca Version 0.32.0
 - Visual Studio code (insider)
Version: 1.96.0-insider (user setup)
Commit: 475acb4b9bdd77d4204224990bf288ed5bfe6b0e
Date: 2024-12-09T22:28:54.579Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22635

**Comment by ps610** [comment]
Hi @Bertverbeek4PS,

can you try to hit the "Refresh"-button at the top of the tree view? You probably deleted a project or repository recently, but the extensions cache is not invalidated yet.

**Comment by Bertverbeek4PS** [comment]
Hi @ps610 did that also. But then I got the same warning:
![image](https://github.com/user-attachments/assets/24eb8f1f-6cee-4f57-a5e3-4e656260a88d)

**Comment by ps610** [comment]
I was able to reproduce the issue and will work on a fix.

**Comment by ps610** [comment]
@Bertverbeek4PS I deployed a fix, it should work now.
