### ISSUE TITLE
[BUG] Can not cancel "Create Deployment" with Esc button (vscode.general.bugReport)

### ISSUE THREAD

**Issue by StefanMaron** [cosmoconsult/alpaca#3]
**Describe the bug**
I clicked on create deployment (AL-Go) just to see how it works.
I pressed Esc multiple times, but it still started the Action on Github.

**To Reproduce**
1. Click on the + sign on deployements on any AL Go Project
2. try to cancel it with Esc

**Expected behavior**
Should be possible to cancel this

**Screenshots**
none

**System Information**
 - OS: [e.g. Windows, MacOS, Linux]
 - Alpaca Version (VS Code Extension) preview v0.17.0

**Additional context**

**Comment by lippertmarkus** [comment]
Thanks, we're looking into handling that better

**Comment by ps610** [comment]
@StefanMaron We have just released version 0.18 of the extension, which fixes this issue, brings some new features and several internal improvements. Please update to this version

**Comment by lippertmarkus** [comment]
Closing this as it's implemented now
