### ISSUE TITLE
[FEATURE] Contianer overview should display project container

### ISSUE THREAD

**Issue by StefanMaron** [cosmoconsult/alpaca#4]
**Is your feature request related to a problem? Please describe.**
When creating containers in relation to a project, its hard to see how many contianers are created and stopped (are they started automatically?) inside the project structure if its collapsed after vs code is restarted.

**Describe the solution you'd like**
I would like to see all cotnainers manually created and from project scope inside the container list. 
If related to a project, they should have at least a property to show this.

**Describe alternatives you've considered**

**Additional context**

**Comment by lippertmarkus** [comment]
We're currently refactoring our container API and will add this when the refactoring is done

**Comment by ps610** [comment]
@StefanMaron We have just released v0.23.0 of the extension, which now implements the container view:
![image](https://github.com/user-attachments/assets/4bfbfe93-2b35-426a-9afd-8195cce6aad7)
