### ISSUE TITLE
[BUG] error creating container named BCApps (VSCode Error One or more validation errors occurred.)

### ISSUE THREAD

**Issue by tscottjendev** [cosmoconsult/alpaca#5]
**Describe the bug**
Getting an error trying to create a container for a BusinessCentralApps project.  Get this error:

> One or more validation errors occurred. (Status 400: One or more validation errors occurred.). Errors: {
>   "Id": [
>     "The Id field is required."
>   ]
> }

**To Reproduce**
1. Go to an AL:GO enabled repository
2. Select "Containers"
3. Click the "+" sign
4. Enter on the name.  In this case the name was BCApps
7. See error

**Expected behavior**
Expect container created with given container name.

**Screenshots**
![image](https://github.com/user-attachments/assets/301cac00-127f-431d-8523-a8733aa44d50)

**System Information**
 - OS: Windows 10
 - Alpaca Version (VS Code Extension) v0.21.0

**Additional context**
I have not used my Alpaca configuration in a while.

**Comment by lippertmarkus** [comment]
Thanks for reporting, we found the issue and are currently working on a fix.

**Comment by lippertmarkus** [comment]
The fix is rolled out now!
