### ISSUE TITLE
[BUG] github org account stopped showing correctly

### ISSUE THREAD

**Issue by NavNab** [cosmoconsult/alpaca#8]
**Describe the bug**
My org account repos are not visible in my vscode using Alpaca.
My personal repos in my account are visible without any problem.
P.S: I'm the global admin of my github org.

**To Reproduce**
N/A

**Expected behavior**
List repos in my org account.

**Screenshots**
<img width="324" alt="image" src="https://github.com/user-attachments/assets/c298eedc-d0b5-49e7-9f46-3d0abe05a92d">

**System Information**
 - OS: Windows 11
 - COSMO Alpaca Preview. Version: 0.26.0

**Additional context**
It was working as expected few days ago.

**Comment by lippertmarkus** [comment]
or did you accidentally hide them in settings? 
<img width="584" alt="image" src="https://github.com/user-attachments/assets/f5ea3dae-ac2e-4c5a-b669-fbd1f3d28b86">

**Comment by NavNab** [comment]
Yes, I have repos configured with AL-Go. Example:
![image](https://github.com/user-attachments/assets/ae4bbc51-4796-4a68-9278-706243668650)

I disabled all settings related to Alpaca, the issue remains.
![image](https://github.com/user-attachments/assets/674e88db-146f-4975-a684-eeb37828f4ad)

I switched between github and azuredevops views. I have the same issue with azuredevops. I can't see my org. But, this is not a big deal for me as I focus on github with Alpaca.

**Comment by NavNab** [comment]
I tested on a fresh windows 11 sandbox and I have the same issue
- fresh vscode installation
- fresh Alpaca installation
- only Alpaca extension is installed

![image](https://github.com/user-attachments/assets/33c26bff-9906-49be-8e1b-75d2f595550b)

**Comment by lippertmarkus** [comment]
In your personal settings under `Appllications ->  Authorized OAuth Applications -> GitHub for VS Code` can you check if you granted access to the orgs?

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/648ff8a0-ebcd-42dc-a5f7-65d29f7f94c5">

**Comment by NavNab** [comment]
I can see both my org and microsoft
![image](https://github.com/user-attachments/assets/25d327a3-ffc4-4910-be0a-20f1ad232bb5)

**Comment by lippertmarkus** [comment]
ok then please check if the requests get correct responses
1. add `"cosmo-alpaca.debugMode": true` to your settings.json
2. `Help > Toggle developer tools` and in those tools switch to console and clear it
3. Reload the repo list with expanded repo list underneath the org account
4. Check the console logs (please don't leak your token in the headers)

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/e581a886-0093-48ae-94bb-0eecd1787a30">

Do you just get an empty array as a response?

If that doesn't show something I think we need to arrange a debugging session together

**Comment by NavNab** [comment]
The debugMode is greyed out (not sure if clearly visible in te screenshot below).
The setting is not available in my version?
I followed the steps; the console is completely empty.

![image](https://github.com/user-attachments/assets/cab04af4-146b-46fd-af27-fcb853d98ef5)

**Comment by lippertmarkus** [comment]
debugMode worked when changing console to verbose log level

The issue leading to organisational repositories not loading was a trailing comma in the settings file. We'll check if we can adapt our backend to handle this as well.

**Comment by lippertmarkus** [comment]
We just rolled out an update. Our backend can now handle trailing commas in all JSON files and shows more helpful messages if it has issues parsing a Json file in case of errors.
