### ISSUE TITLE
[QUESTION] maybe a bug?

### ISSUE THREAD

**Issue by NavNab** [cosmoconsult/alpaca#9]
I manually deleted an environment in my github org account. Now I have the error below in vscode using Alpaca for github.

![image](https://github.com/user-attachments/assets/b1d2700e-eb16-4d90-8dab-72842171fcd1)

Name: COSMO Alpaca Preview
Version: 0.26.0

**Comment by lippertmarkus** [comment]
Is the environment still present in `.github/AL-Go-Settings.json`?

**Comment by NavNab** [comment]
It was still present. I deleted it but the error remained.
Now I can't re-check because of the other problem I have https://github.com/cosmoconsult/alpaca/issues/8

**Comment by lippertmarkus** [comment]
removing the environment manually from the settings file as a workaround did help. We'll check how we can handle those cases more gracefully

**Comment by NavNab** [comment]
Indeed, manually removing the env from setting resolved the issue.
Thank you
